name: MuleSoft CI/CD Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Run conftest (OPA)
      run: |
        LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
        ARCH=$(arch)
        SYSTEM=$(uname)
        wget "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_${SYSTEM}_${ARCH}.tar.gz"
        tar xzf conftest_${LATEST_VERSION}_${SYSTEM}_${ARCH}.tar.gz
        sudo mv conftest /usr/local/bin
        
    - name: Run Policy Tests
      run: |
        conftest test src/main/resources/properties/properties.yaml --policy policy/testRule.rego
      #conftest test src/main/resources/properties/dependency.json --policy policy/dependency.rego

    - name: Build Application
      run: mvn clean package
    - name: Upload artifact 
      uses: actions/upload-artifact@v4
      with:
          name: artifacts
          path: target/*.jar
    - name: Deploy to CloudHub
      
      env:
        ANYPOINT_USERNAME: b7867ab9bc4948b29565b1118bedcc98
        ANYPOINT_PASSWORD: 54C6704FB6Af432aB8A9DAB0Ec15cFD2
        ANYPOINT_ENV: 'Sandbox'
        ANYPOINT_ORG_ID: 'a247db8b-0426-40f8-adca-afb1b5bf5cc4'
        ANYPOINT_BUSINESS_GROUP: 'MyCo'

      run: |
        mvn mule:deploy \
        -DmuleDeploy \
        -Dmule.artifact=/home/runner/work/mule-repo/mule-repo/target/u-fraud-api-1.0.0-SNAPSHOT-mule-application.jar
        -Danypoint.username==${{ env.ANYPOINT_USERNAME }} \
        -Danypoint.password=${{ env.ANYPOINT_PASSWORD }} \
        -Denv=${{ env.ANYPOINT_ENV }} \
        -Danypoint.platform.organization=${{ env.ANYPOINT_ORG_ID }} \
        -Danypoint.platform.businessGroup=${{ env.ANYPOINT_BUSINESS_GROUP }} \
        -Danypoint.platform.target=CloudHub \
        -Danypoint.platform.region=us-east-1 \
        -Danypoint.platform.workerType=MICRO \
        -Danypoint.platform.workers=1
